---
title: "openEBGM"
output: html_notebook
---

```{r}
install.packages("openEBGM")
```

```{r}
library(openEBGM)
```

```{r}
data(caers)
processed <- processRaw(caers, zeroes=FALSE)
head(processed[order(processed$var2, processed$var1),])
```

```{r}
# squash and save squashed data
squashed <- autoSquash(processed)
write.csv(squashed, "C:/Users/farrowg/Documents/vigipy_devops/data/squashed_data.csv")

# saves caers dataset
write.csv(caers, "C:/Users/farrowg/Documents/vigipy_devops/data/caers_data.csv")
```

```{r}
# estimate hyperparameters for this function
theta_init <- data.frame(alpha1 = c(0.2, 0.1, 0.3),
                         beta1  = c(0.1, 0.2, 0.5),
                         alpha2 = c(2,   10,  6),
                         beta2  = c(4,   10,  6),
                         p      = c(1/3, 0.2, 0.5)
)

opt <- autoHyper(data = processed, theta_init = theta_init, squashed=FALSE, 
                 zeroes=FALSE, N_star=1)
```

```{r}
# given these values for the priors, calculate the different signals 
theta_hat <- opt$estimates
qn <- Qn(theta_hat, N = processed$N, E = processed$E)

processed$EBGM <- ebgm(theta_hat, N=processed$N, E=processed$E, qn=qn)
processed$QUANT_05 <- quantBisect(5, theta_hat = theta_hat,
                                  N = processed$N, E = processed$E, qn = qn)
processed$QUANT_95 <- quantBisect(95, theta_hat = theta_hat,
                                  N = processed$N, E = processed$E, qn = qn)
processed$log2 <- log2(processed$EBGM)
processed <- processed[order(-processed$log2), ]
processed_trim <- subset(processed, select = -c(RR, PRR, EBGM, QUANT_95, N, E))

head(processed_trim)
```